package com.facturasapi.rest.bean;
// Generated 10-dic-2013 19:27:17 by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String usuario;
     private String password;
     private byte[] key;
     private byte[] cert;
     private String clave;

    public Usuario() {
    }

	
    public Usuario(int id, String nombre, String usuario, String password) {
        this.id = id;
        this.nombre = nombre;
        this.usuario = usuario;
        this.password = password;
    }
    public Usuario(int id, String nombre, String usuario, String password, byte[] key, byte[] cert, String clave) {
       this.id = id;
       this.nombre = nombre;
       this.usuario = usuario;
       this.password = password;
       this.key = key;
       this.cert = cert;
       this.clave = clave;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getKey() {
        return this.key;
    }
    
    public void setKey(byte[] key) {
        this.key = key;
    }
    public byte[] getCert() {
        return this.cert;
    }
    
    public void setCert(byte[] cert) {
        this.cert = cert;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


